2025-02-07T17:50:34 {"cpu": 0.1923828125, "cpu_total": 12, "cpu_usage": 0.016031901041666668, "memory": 1616.0, "memory_total": 9815.0, "memory_usage": 0.16464595007641367, "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Pipeline training_models for run 22 in schedule 1 is alive.", "timestamp": 1738950634.862948, "uuid": "266f18413c3643189945e3c447722ff6"}
2025-02-07T17:50:35 {"cpu": 0.19677734375, "cpu_total": 12, "cpu_usage": 0.016398111979166668, "memory": 1650.0, "memory_total": 9815.0, "memory_usage": 0.16811003565970453, "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Pipeline training_models for run 22 in schedule 1 is alive.", "timestamp": 1738950635.300192, "uuid": "35448ea96dfe401fbdfaa5612e1dae39"}
2025-02-07T17:50:35 {"block_run_id": 204, "block_uuid": "loading_data", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 204: pipeline training_models block loading_data", "timestamp": 1738950635.300779, "uuid": "c48207c2ab264e32afc9d21bf2e57e1e"}
2025-02-07T17:50:34 {"block_run_id": 204, "block_uuid": "loading_data", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 204 (block_uuid: loading_data) completes.", "timestamp": 1738950634.935078, "uuid": "f6e207cb305d43d1ae877146663810b5"}
2025-02-07T17:50:35 {"block_run_id": 206, "block_uuid": "model_selection", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 206: pipeline training_models block model_selection", "timestamp": 1738950635.041113, "uuid": "1bb21ee86a0c41469e87e2082295bb07"}
2025-02-07T17:50:35 {"block_run_id": 206, "block_uuid": "model_selection", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 206 (block_uuid: model_selection) completes.", "timestamp": 1738950635.484257, "uuid": "834a784fecd64abe8f22ed72d2894ecb"}
2025-02-07T17:50:43 {"cpu": 0.1953125, "cpu_total": 12, "cpu_usage": 0.016276041666666668, "memory": 1615.0, "memory_total": 9815.0, "memory_usage": 0.16454406520631687, "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Pipeline training_models for run 22 in schedule 1 is alive.", "timestamp": 1738950643.432928, "uuid": "f8282d10fc1442c0bb375362eb67c7de"}
2025-02-07T17:50:43 {"block_run_id": 205, "block_uuid": "preprocessing_data", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 205: pipeline training_models block preprocessing_data", "timestamp": 1738950643.863085, "uuid": "83b9fa0f6b214ddf8370167433d3c479"}
2025-02-07T17:50:46 {"block_run_id": 205, "block_uuid": "preprocessing_data", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 205 (block_uuid: preprocessing_data) completes.", "timestamp": 1738950646.207851, "uuid": "d419da22212843948b4574ce2eb7e39d"}
2025-02-07T17:50:53 {"cpu": 0.20263671875, "cpu_total": 12, "cpu_usage": 0.016886393229166668, "memory": 1621.0, "memory_total": 9815.0, "memory_usage": 0.1651553744268976, "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Pipeline training_models for run 22 in schedule 1 is alive.", "timestamp": 1738950653.949826, "uuid": "09440f3046374fb2940f52ac32f06f0f"}
2025-02-07T17:50:54 {"block_run_id": 207, "block_uuid": "lasso_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 207: pipeline training_models block lasso_trainer", "timestamp": 1738950654.382648, "uuid": "ccef9b3f519c4c6da7ac709ad81f3c6a"}
2025-02-07T17:50:55 {"block_run_id": 208, "block_uuid": "knn_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 208: pipeline training_models block knn_trainer", "timestamp": 1738950655.561026, "uuid": "c465c33a0039446aaa5e05ff3fcb7fce"}
2025-02-07T17:50:55 {"block_run_id": 209, "block_uuid": "rf_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 209: pipeline training_models block rf_trainer", "timestamp": 1738950655.580624, "uuid": "d05f63e50b544bd3bd9eb72e8f784e7e"}
2025-02-07T17:50:55 {"block_run_id": 210, "block_uuid": "dt_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 210: pipeline training_models block dt_trainer", "timestamp": 1738950655.616828, "uuid": "4c68ba32b207493791cf5de282dae661"}
2025-02-07T17:50:55 {"block_run_id": 211, "block_uuid": "ridgee_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 211: pipeline training_models block ridgee_trainer", "timestamp": 1738950655.616907, "uuid": "b7511ba9b7eb4ba096296f96c7cefc48"}
2025-02-07T17:50:55 {"block_run_id": 213, "block_uuid": "load_intopostgres", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Execute PipelineRun 22, BlockRun 213: pipeline training_models block load_intopostgres", "timestamp": 1738950655.67052, "uuid": "ee6a4c32459b4e11bcc3e33187c7dba9"}
2025-02-07T17:50:55 {"block_run_id": 211, "block_uuid": "ridgee_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 211 (block_uuid: ridgee_trainer) completes.", "timestamp": 1738950655.988486, "uuid": "dd3bdd3c3baf4f27b55d408dc5c302b6"}
2025-02-07T17:50:56 {"block_run_id": 210, "block_uuid": "dt_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 210 (block_uuid: dt_trainer) completes.", "timestamp": 1738950656.042183, "uuid": "00206232b1ce4cc0a04fae4f8ddbe4bd"}
2025-02-07T17:50:56 {"block_run_id": 209, "block_uuid": "rf_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 209 (block_uuid: rf_trainer) completes.", "timestamp": 1738950656.102736, "uuid": "3b3622c4d9904d319a8fe261d156d031"}
2025-02-07T17:50:56 {"block_run_id": 207, "block_uuid": "lasso_trainer", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "EXCEPTION", "message": "BlockRun 207 (block_uuid: lasso_trainer) failed.", "timestamp": 1738950656.254773, "uuid": "95ba98535f8a492aa91040dc448fb531", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in transform_custom\nNameError: name 'Ridge' is not defined\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "name 'Ridge' is not defined"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in transform_custom
NameError: name 'Ridge' is not defined
2025-02-07T17:50:56 {"block_run_id": 213, "block_uuid": "load_intopostgres", "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "BlockRun 213 (block_uuid: load_intopostgres) completes.", "timestamp": 1738950656.431448, "uuid": "f0ff61bfeba3466da86d2ee6cdf1b8e3"}
2025-02-07T17:51:03 {"cpu": 0.216796875, "cpu_total": 12, "cpu_usage": 0.01806640625, "memory": 1721.0, "memory_total": 9815.0, "memory_usage": 0.17534386143657668, "pipeline_run_id": 22, "pipeline_schedule_id": 1, "pipeline_uuid": "training_models", "hostname": "b262786611bb", "level": "INFO", "message": "Pipeline training_models for run 22 in schedule 1 is alive.", "timestamp": 1738950663.99871, "uuid": "6ad565fa7bfd4236835fe589c1ab3225"}
